library(tidyverse)
library(tundra)

file_path <- "/media/ross/external/Copying_files/AlexandraFiord_CompiledData/AlexandraFiord_Phenology/AlexandraFiord_Phenology.csv"
output_dir <- "/home/ross/Desktop/compiled_phenology/"

clean_cassandra_K_phenology <- function(file_path, output_dir){
  # If output dir does not exist then create it
  if (!dir.exists(output_dir)){
    dir.create(output_dir, recursive = TRUE)
  }
  # load file
  pheno_data <- read.csv(file_path)
  # Create column syn list
  col_syns_lists <- create_col_syn_list()
  # Cycle through each list of col syns.
  # Rename the columns that are to be renamed
  for (name_pair in col_syns_lists$name_change_list){
    pheno_data <- pheno_data %>% rename("{name_pair[1]}" := .data[[name_pair[2]]])
  }
  for (col_syns_list in col_syns_lists$syn_lists){
    # For each col after the first in col_syn_list, if column 1 is empty and current column is not
    # then set column 1 to equal contents of current column. If both are empty leave column one as is.
    # If both columns contain data then set column one to contain its current data with that of the current
    # column appended, separated by "_._". Empty is defined as NA, Null, or "".
    for (i in 2:length(col_syns_list)){
      pheno_data <- pheno_data %>% rowwise() %>%
        mutate("{col_syns_list[1]}" := ifelse(is.empty(.data[[col_syns_list[1]]]) & !is.empty(.data[[col_syns_list[i]]]),
                                            as.character(.data[[col_syns_list[i]]]),
                                             ifelse(!is.empty(.data[[col_syns_list[1]]]) & !is.empty(.data[[col_syns_list[i]]]),
                                                    paste0(.data[[col_syns_list[1]]], "_._", col_syns_list[[i]], ": ",  .data[[col_syns_list[i]]]),
                                                    as.character(.data[[col_syns_list[1]]])))
        )
    }
  }
  # Create a unique plot_id for all data with sufficient plot identifying info, infer treatment data that
  # may be missing if a plot can be identified, and standardise the site, plot, and treatment variables to
  # be consistent across all compiled data files.
  pheno_data <- standardise_plots(pheno_data, output_dir, "")
  # Remove all synonym columns that had their data copied into other columns, as well as lauras_plots,
  # which is now redundant given the plot_ids generated by standardise_plots, and is also incomplete
  pheno_data <- pheno_data %>% select(!any_of(c(col_syns_lists$cols_to_remove, "lauras_plots")))
  # Reorder the columns to group the plot identifying data, date data, pheno, trait, and ill understood data
  pheno_data <- pheno_data %>% relocate(plot_id, site, plot, year, first_day, last_day, species,
                                      plant_id, contains("treatment"), starts_with("pheno"), starts_with("trait"),
                                      starts_with("NA"))
  write_csv(pheno_data, paste0(output_dir, "/compiled_phenology.csv"))
  pheno_data
}

create_col_syn_list <- function(){
  col_syn_lists <- list(
    name_change_list = list(
      c("Plant-ID", "Plant"),
      c("First-day", "First_day"),
      c("Last-day", "Last_day"),
      c("Salix-Sex", "Sex"),
      c("Pheno_Leaf_new", "Leaf_new"),
      c("Pheno_Leaf_mature", "Leaf_mat"),
      c("Pheno_Leaf_senescence", "Leaf_sen"),
      c("Pheno_Leaf_disease_fungus", "Leaf_fungus"),
      c("Pheno_Leaf_disease_mites", "Leaf_mites"),
      c("Pheno_Leaf_herbivory", "Leaf_eaten"),
      c("Pheno_Leaf_mat_sen", "Leaf_mat_sen"),
      c("Pheno_Flower_bud_first", "Flower_bud_first"),
      c("Pheno_Flower_bud_last", "Flower_bud_last"),
      c("Pheno_Flower_bud_break_first",	"Flower_bbk_first"),
      c("Pheno_Flower_bud_break_last",	"Flower_bbk_last"),
      c("Pheno_Flower_bbk_and_elong",	"Flower_bbk_and_elong"),
      c("Pheno_Flower_elongated_first",	"Flower_elong_first"),
      c("Pheno_Flower_elongated_last",	"Flower_elong_last"),
      c("Pheno_Flower_open_petals",	"Flower_open_first"),
      c("Pheno_Flower_mature_first",	"Flower_mat_first"),
      c("Pheno_Flower_mature_last",	"Flower_mat_last"),
      c("Pheno_Flower_expansion_ArcLat",	"Flower_exp"),
      c("Pheno_Flower_senescence_first",	"Flower_sen_first"),
      c("Pheno_Flower_senescence_last",	"Flower_sen_last"),
      c("Pheno_Flower_fruit_immature_first",	"Cap_imm_first"),
      c("Pheno_Flower_fruit_immature_last",	"Cap_imm_last"),
      c("Pheno_Flower_fruit_mature_first",	"Cap_ripe_first"),
      c("Pheno_Flower_fruit_mature_last",	"Cap_mat_last"),
      c("Pheno_Flower_petal_fall",	"Petal_fall_first"),
      c("Pheno_Flower_abort_unfert_fungus_eaten",	"Abort_unfert_fungus_eaten"),
      c("Pheno_Flower_aborted",	"Abort"),
      c("Pheno_Flower_peduncle_broke",	"Pd_brkn"),
      c("Pheno_Fungus",	"Fungus_date"),
      c("Pheno_Flower_herbivory",	"Flower_herb"),
      c("Pheno_Herbivory",	"Herb"),
      c("Pheno_Growth_ceased_Cassiope",	"Growth_ceased"),
      c("Trait_Date_AGI_meas",	"Newgrowth_measurement_date"),
      c("Trait_Date_counts_height_meas",	"Flower_height_measurement_date"),
      c("Trait_Date_height_max",	"Flower_height_max_date"),
      c("Trait_Flower_height",	"Flower_height"),
      c("Trait_Flower_height_avg",	"Flower_height_avg"),
      c("Trait_Flower_height_max",	"Flower_height_max"),
      c("Trait_Peduncle_height",	"Pedcl_height"),
      c("Trait_Percent_green",	"Percent_green"),
      c("Trait_Plant_diameter_axis_1_saxopp",	"Axis_1"),
      c("Trait_Plant_diameter_axis_2_saxopp",	"Axis_2"),
      c("Trait_Rosets_alive",	"Rosets_alive"),
      c("Trait_Leaf_length_green",	"Green_leaf_length"),
      c("Trait_Leaf_length_total",	"Leaf_tot_length"),
      c("Trait_AGI_max",	"Newgrowth_max"),
      c("Trait_AGI_meas",	"Newgrowth"),
      c("Trait_Catkin_length_avg",	"Catkin_length_avg"),
      c("Trait_Catkin_length_max",	"Catkin_length_max"),
      c("Trait_Leaf_new_no",	"Leaf_new_no"),
      c("Trait_Leaf_mature_no",	"Leaf_mat_no"),
      c("Trait_Leaf_senescence_no",	"Leaf_sen_no"),
      c("Trait_Leaf_total_no",	"Leaf_no"),
      c("Trait_Flower_total_per_plant_no",	"Flower_total_no"),
      c("Trait_Flower_bud_no",	"Flower_bud_no"),
      c("Trait_Flower_bud_break_no",	"Flower_bbk_no"),
      c("Trait_Flower_elongated_no",	"Flower_elong_no"),
      c("Trait_Flower_open_petals_no",	"Flower_open_no"),
      c("Trait_Flower_mature_no",	"Flower_mat_no"),
      c("Trait_Flower_senescence_no",	"Flower_sen_no"),
      c("Trait_Flower_Fruit_immature_no",	"Cap_imm_no"),
      c("Trait_Flower_Fruit_mature_no",	"Cap_mat_no"),
      c("Trait_Flower_Seed_disp_no",	"Seed_disp_no"),
      c("Trait_Flower_Fertilized_no",	"Fertilized_no"),
      c("Trait_Flower_Aborted_no",	"Aborted_no"),
      c("Trait_Flower_herbivory_no",	"Flower_herb_no"),
      c("Trait_OldFlowersPastYear_no",	"Flower_no_old"),
      c("NA_Branch",	"Branch"),
      c("NA_Cap_fall",	"Cap_fall"),
      c("NA_Dendro_distance_from_centre_m",	"Dendro_distance_from_centre_m"),
      c("NA_Est_date",	"Est_date"),
      c("NA_Flowers_plot_max",	"Flower_plot_max"),
      c("NA_Flowers_per_plot",	"Flowers_per_plot"),
      c("NA_Fungus",	"Fungus"),
      c("NA_Late_seas",	"Late_seas"),
      c("NA_Missed_pheno",	"Missed_pheno"),
      c("NA_Mysterious_see_comments_sheet",	"Mysterious_see_comments_sheet"),
      c("NA_Original_bud_exp",	"Original_bud_exp"),
      c("NA_Plant_no",	"Plant_no"),
      c("NA_Replicate",	"Replicate"),
      c("NA_Salix_Veg_Rep",	"Veg_rep"),
      c("NA_Seed_col",	"Seed_col"),
      c("NA_Seed_col_date",	"Seed_col_date"),
      c("NA_Tip_colour_Cassiope",	"Tip_colour")
      
    ),
    syn_lists = list(
      c("Pheno_Flower_elongated_first",	"Elong_first",	"Elong_old",	"Pd_elong",	"Catkin_imm", "Pheno_Flower_bbk_and_elong"),	
      c("Pheno_Flower_elongated_last",	"Elong_last"),									
      c("Pheno_Flower_mature_first",	"Poll_first"),									
      c("Pheno_Flower_senescence_first",	"Petal_sen_first",	"Sen_first",	"Unisex_senescence",	"Flower_sen_male"),						
      c("Pheno_Flower_senescence_last",	"Petal_sen_last"),									
      c("Pheno_Flower_fruit_immature_first",	"Seed_imm_cap_cap_twist_fem_swell",	"Cap_twist",	"Female_swell"),							
      c("Pheno_Flower_fruit_immature_last",	"Frt_imm_last"),
      c("Pheno_Flower_fruit_mature_first",	"Cap_first",	"Frt_mat_first", "Seed_fall",	"Seed_disp_cap_mat"),
      c("Pheno_Flower_fruit_mature_last",	"Cap_last",	"Cap_ripe_last",	"Cap_open_last",	"Seed_set_last"),					
      c("Pheno_Flower_aborted",	"Unfertilized"),
      c("Pheno_Flower_bud_break_first", "Pheno_Flower_bbk_and_elong"),
      c("Trait_Date_counts_height_meas", "Catkin_measurement_day",	"Peduncle_measurement_date"),		
      c("Trait_Flower_height_avg",	"Seas_flower_height_avg",	"Flower_height_top_avg"),
      c("Trait_Flower_height_max",	"Seas_flower_height_max",	"Flower_height_top_max"),
      c("Trait_Peduncle_height",	"Flower_height_sub"),		
      c("Trait_Percent_green",	"Percent_green_max"),
      c("Trait_Rosets_alive",	"Ramets_rosets_alive_no",	"Ramets_no"),				
      c("Trait_Leaf_length_total",	"Tot_length",	"Leaf_length"),		
      c("Trait_AGI_meas",	"Agi",	"Stem_length",	"Leaf_shoot_no"),			
      c("Trait_Leaf_mature_no",	"Green_leaf_no",	"First_leaf_mat_no"),			
      c("Trait_Leaf_total_no",	"Leaf_no_max"),
      c("Trait_Flower_total_per_plant_no",	"Flower_no",	"Flower_no_max",	"Flower_shoot_no",	"Fpc"),
      c("Trait_Flower_bud_no",	"Flower_bud_max"),
      c("Trait_Flower_bud_break_no",	"Flower_bbk_total_no",	"Flower_bbk_max"),				
      c("Trait_Flower_elongated_no",	"Flower_elong_total_no",	"Elong_no"),	
      c("Trait_Flower_mature_no",	"Flower_mat_total_no",	"Flower_mat_max",	"Poll_no",	"Pollen_total_no"),		
      c("Trait_Flower_senescence_no",	"Petal_sen_no",	"Petal_wilt_total_no",	"Petal_fall_no",	"Flower_sen_total_no",	"Flower_sen_max"),	
      c("Trait_Flower_Fruit_immature_no",	"Cap_imm_total_no",	"Frt_imm_no"),
      c("Trait_Flower_Fruit_mature_no",	"Cap_mat_total_no",	"Frt_mat_no",	"Cap_ripe_total_no",	"Cap_max",	"Cap_total_no"),	
      c("Trait_Flower_Seed_disp_no",	"Seed_fall_no",	"Frt_deh_no",	"Seed_disp_max"),		
      c("Trait_Flower_Aborted_no",	"Aborted_total_no")
    )
  )
  cols_to_remove <- vector("character")
  for (syn_list in col_syn_lists$syn_lists){
    cols_to_remove <- append(cols_to_remove, syn_list[2:length(syn_list)])
  }
  col_syn_lists <- c(col_syn_lists, list(cols_to_remove = cols_to_remove))
  col_syn_lists
}

# A function which searches the dataframe for columns which overlap, based on the fact
# that clean_cassandra_k_phenology combines overlapping data separated by "_._".
# This function accepts a dataframe and outputs a printed list of the names of all
# overlapping columns and all unique examples of the overlapping data
find_overlapping_columns <- function(dataframe){
  # For every column in the dataframe search for the presence of "_._". If it is present
  # extract and print the names of the overlapping columns as well as the unique overlapping
  # data
  for (col in names(dataframe)){
    if (sum(grepl(pattern = "_._", data[[col]])) > 0){
      
      string <- unique(dataframe[[col]][grepl(":", dataframe[[col]])])
      # remove the column separator and everything before it from the data. This should leave
      # the name of the overlapping column followed by ": <data>"
      overlap_col <- sub(".*_\\._", "", string)
      # Remove the data to leave behind only the name of the offending column
      overlap_col <- sub(":.*", "", overlap_col)
      # extract the data before the column separator
      col_data <- sub("(.*)_\\._.*", "\\1", string)
      # Extract the data following the colon
      other_data <- sub(".*: ", "", string)
      print(paste(col, "__overlaps with__", unique(overlap_col)))
      print(paste(col_data, other_data))
    }
  }
}
